// <auto-generated />
using System;
using Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(ZettelkaschdeContext))]
    [Migration("20250312192844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Core.DataTypes.FachData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("KaschdeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ZeddelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KaschdeId");

                    b.HasIndex("ZeddelId");

                    b.ToTable("FachData");
                });

            modelBuilder.Entity("Core.Kaschde", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KaschdeList");
                });

            modelBuilder.Entity("Core.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ZeddelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ZeddelId");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("Core.Zeddel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ZeddelList");
                });

            modelBuilder.Entity("Core.DataTypes.FachData", b =>
                {
                    b.HasOne("Core.Kaschde", null)
                        .WithMany("Fach")
                        .HasForeignKey("KaschdeId");

                    b.HasOne("Core.Zeddel", "Zeddel")
                        .WithMany()
                        .HasForeignKey("ZeddelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zeddel");
                });

            modelBuilder.Entity("Core.Topic", b =>
                {
                    b.HasOne("Core.Zeddel", null)
                        .WithMany("Topics")
                        .HasForeignKey("ZeddelId");
                });

            modelBuilder.Entity("Core.Kaschde", b =>
                {
                    b.Navigation("Fach");
                });

            modelBuilder.Entity("Core.Zeddel", b =>
                {
                    b.Navigation("Topics");
                });
#pragma warning restore 612, 618
        }
    }
}
